### ISSUE TITLE
Missing Import mysql

### ISSUE THREAD

**Issue by satriarrrrr** [ahartanto/morphling#1]
Panic arises when I try to open a database connection. Below is the panic message that I got:
`panic: failed dial database : sql: unknown driver "mysql" (forgotten import?)`

It seems we are missing import github.com/go-sql-driver/mysql for the side effect.

**Comment by ahartanto** [comment]
@satriarrrrr as in example ,

u should  import _ "github.com/go-sql-driver/mysql" on your function that call morphling. Morphling is an abstraction to the database , so its need an additional imported driver package

will close the issue thanks
